//Write a program demonstrating Exception handling using try, catch and finally for handling a Arithmetic Exception and Array Index Out of Bounds Exception

package exception_handling;

//Class declaration for ExceptionHandling
public class ExceptionHandling { 
	
	// Main method declaration
    public static void main(String[] args) { 
      
    	// declaring variables
        int a, b, c; // Declaration of integer variables a, b, and c
        a = 20; 
        b = 0; 
        //b=0;
        System.out.println("start of the program"); // Printing start message

        // try statement:block of statements that may throw an exception.
        try {
            // division by zero, will throw ArithmeticException,if b=0;
            c = a / b; // Performing division.
            System.out.println("c=" + c); // Printing the result of division

            // accessing an index out of bounds will throw ArrayIndexOutOfBoundsException
            //int arr[] = { 1, 2, 3 }; // Initializing an array with three elements
            //System.out.println(arr[4]); // Accessing index 4 of the array which occurs an exception.

        } catch (ArithmeticException ae) { // Catch block for ArithmeticException
        	//catch,catches exceptions generated by try statements.
            
        	System.out.println("Arithmetic Exception caught"); // Printing exception.

        }
        try{
        	int arr[] = { 1, 2, 3 }; // Initializing an array with three elements
            System.out.println(arr[4]); // Accessing index 4 of the array which occurs an exception.
        }catch (ArrayIndexOutOfBoundsException ae) { // Catch block for ArrayIndexOutOfBoundsException
        
            
           System.out.println("Array Exception caught"); // Printing exception.

        } finally {
            
        	// finally block executes whether an exception occurred or not
            System.out.println("end of the program"); // Printing statement.
        }
    }
}
